#206: Implemented UninstallCommandlet
devonfw/IDEasy pull request #258
Opened 2024-03-20 14:17 UTC by ndemirca

2024-03-20 16:11 UTC, mvomiero requested changes
Nice implementation for this commandlet! 👍   just some small fixes suggested, other then that LGTM

2024-03-20 16:11 UTC, mvomiero commented on cli/src/main/java/com/devonfw/tools/ide/commandlet/UninstallCommandlet.java
> +        throw new IllegalStateException("Couldn't uninstall " + commandletName);
Maybe you have to rethrow the original exception in order to preserve the stacktrace, as in the coding conventions?
`throw new IllegalStateException("Couldn't uninstall " + commandletName, e);`

https://github.com/devonfw/IDEasy/blob/main/documentation/coding-conventions.adoc#catching-and-handling-exceptions

2024-03-20 16:11 UTC, mvomiero commented on cli/src/test/java/com/devonfw/tools/ide/commandlet/UninstallCommandletTest.java
> +    Path softwarePath = context.getSoftwarePath();
The variable is unused

2024-03-20 16:11 UTC, mvomiero commented on cli/src/test/java/com/devonfw/tools/ide/commandlet/UninstallCommandletTest.java
> +    Path softwarePath = context.getSoftwarePath();
the variable is unused

2024-03-20 16:45 UTC, salimbouch commented
Just a suggestion, but maybe you could delegate the uninstall process to LocalToolCommandlet just like you described in #206, it seems cleaner.

2024-03-21 08:33 UTC, ndemirca commented on cli/src/test/java/com/devonfw/tools/ide/commandlet/UninstallCommandletTest.java
> +    Path softwarePath = context.getSoftwarePath();
It was test variable, sorry!

2024-03-27 09:50 UTC, mvomiero approved these changes

2024-04-15 08:58 UTC, hohwille approved these changes
@ndemirca Thanks for your PR. All looking good and ready for merge 👍 
FYI: As nice to have remark, the methods like `testUninstallCommandletRun_WithExistingCommandlet()` are not as intuitive as the commandlets always exist. A more compact and self-explaining name could be `testUninstallWithAlreadyInstalledTool` (and `testUninstallWithoutInstalledTool`).

But nothing wrong here. Thanks for your nice work 👍

2024-04-15 09:00 UTC, merged