#531: prevent logging from context constructor
devonfw/IDEasy pull request #559
Opened 2024-08-26 20:23 UTC by hohwille

fixes #531
* prevent logging from IdeContext constructor
* check if debug/trace logging was activated before disabling log-levels for processable output commandlets
* solve ContextCommandlet init issues

2024-08-26 20:26 UTC, hohwille commented
@hohwille wrote
>Thank you for this helpful tweak. I would love to include this into an OSS product IDEasy licensed under ASL2.0 and therefore would like to kindly ask for your confirmation. I will leave your files as is including the headers with Author and Link to this page.
This way Windows users that install this product will already have the *.reg files on their disc and only need to merge them.

Brink (Administrator) responded:
> Hello, and welcome. :alien:
That'll be fine.

2024-08-27 11:00 UTC, jan-vcapgemini requested changes
Thanks for your addition of the IdeStartContext. I've added some small CR's but I think overall this is ready to merge.

2024-08-27 11:00 UTC, jan-vcapgemini commented on cli/src/main/java/com/devonfw/tools/ide/context/IdeStartContext.java
> +public interface IdeStartContext extends IdeLogger {
Please add Javadoc.

2024-08-27 11:00 UTC, jan-vcapgemini commented on cli/src/main/java/com/devonfw/tools/ide/context/IdeStartContextmpl.java
> +public class IdeStartContextmpl implements IdeStartContext {
Please check Javadoc.

2024-08-29 06:59 UTC, merged