#556: update PATH on pc run
devonfw/IDEasy pull request #614
Opened 2024-09-12 11:13 UTC by hohwille

fixes #556 
* add `withPathEntry(Path)` method for future implementations of `setEnvironment` methods
* add ability to create a modified `SystemPath` via `withPath` method
* change ProcessContext to track PATH changes and apply them only in `run` method
* also move the code to find the binary executable to `run` method using the final PATH
* improved logging

2024-09-16 10:24 UTC, jan-vcapgemini requested changes
LGTM. Added some small CRs.

2024-09-16 18:01 UTC, hohwille commented on cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java
> +  public SystemPath withPath(String overriddenPath, List<Path> extraPathEntries) {
Done.

2024-09-16 18:01 UTC, hohwille commented on cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java
> -  public SystemPath(IdeContext context, String envPath, Path ideRoot, Path softwarePath, char pathSeparator) {
Done.

2024-09-16 18:01 UTC, hohwille commented on cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java
> +    this(context, envPath, ideRoot, softwarePath, File.pathSeparatorChar, Collections.emptyList());
What is wrong here? IMHO false positive.

2024-09-17 19:35 UTC, jan-vcapgemini commented on cli/src/main/java/com/devonfw/tools/ide/common/SystemPath.java
> +    this(context, envPath, ideRoot, softwarePath, File.pathSeparatorChar, Collections.emptyList());
Jup, was a false positive, sorry.

2024-09-17 19:35 UTC, jan-vcapgemini approved these changes
Ready to merge.

2024-09-19 07:24 UTC, merged