#646: Add variable for intellij to disable console log output
devonfw/IDEasy pull request #729
Opened 2024-10-30 09:27 UTC by KianRolf

Implements: #646

- gives the user the possibility to enable or disable console log output via IDE_ENABLE_LOG
- is set to false by default
- so far is only affecting intellij but intended as a switch for all ide

2024-10-30 15:00 UTC, jan-vcapgemini requested changes
@KianRolf  thanks for your addition of the IDE_ENABLE_LOG variable. I've added some CRs, please resolve.

2024-10-30 15:00 UTC, jan-vcapgemini commented on CHANGELOG.adoc
> +
Please remove.
```suggestion
```

2024-10-30 15:00 UTC, jan-vcapgemini commented on cli/src/main/java/com/devonfw/tools/ide/variable/IdeVariables.java
> +  VariableDefinitionBoolean IDE_ENABLE_LOG = new VariableDefinitionBoolean("IDE_DISABLE_LOG", null, c -> false);
Be aware, the name has a discrepancy.
```suggestion
  VariableDefinitionBoolean IDE_ENABLE_LOG = new VariableDefinitionBoolean("IDE_ENABLE_LOG", null, c -> true);
```

2024-11-04 10:24 UTC, jan-vcapgemini requested changes
Thanks for addressing the change requests. I think we should also add an entry to our documentation, so the user becomes aware of this feature.

2024-11-04 13:56 UTC, jan-vcapgemini commented
I'm not sure about the naming yet. IDE_ENABLE_LOG could be misinterpreted that the logging is now being done into a file. Maybe we need 2 variables instead? IDE_ENABLE_FILE_LOG (logs intellij errors into log file) and IDE_ENABLE_LOG (disables complete logging)

2024-11-11 17:15 UTC, jan-vcapgemini approved these changes
Nice solution for the naming. Ready for review.

2024-11-19 09:23 UTC, jan-vcapgemini approved these changes

2024-11-22 00:24 UTC, hohwille requested changes
@KianRolf this PR should fix #646 and you nicely introduced and documented a new variable for this feature.
However, that variable is not used anywhere in the code so it has no effect yet.
Before merging this PR, we also need to add this effect to make the story complete.
Otherwise after merge, we have a documentation promising a feature that is actually not there and we had stuff like that recently what confused our pilot users.
Please add a change that will redirect the output to a log-file according to the value of this new property.
IMHO this should not only happen for IntelliJ but for any tool we run as `BACKGROUND` as you already implied by the documentation.
Maybe we might even think of a more precise name for the variable since `IDE_ENABLE_CONSOLE_LOG` may imply that all console output is written to a logfile what is actually not the case.

2024-11-22 10:26 UTC, KianRolf commented
PR will be closed for now, since it is still unclear how we will handle console logging from other IDEs, and intellij console log will be disabled by default.

2024-11-22 10:26 UTC, closed without merging