#898 improved feedback messages
devonfw/IDEasy pull request #903
Opened 2024-12-19 12:04 UTC by WorkingAmeise

Closes: #898 
Edition/VersionGetCommandlet changed them to log the configured option if the tool is not installed and the installed option if it is installed.
Changed the toolInstallInfo method to log into IdeSublogger instead of using context.info or context.warning.
Changed the uninstall commandlet to log a warning in case the requested commandlet is not installed.
Changed the uninstallPlugin commandlet to give feedback wether the plugin could be deleted or if there was not installation found.
Adjusted Tests for Edition/VersionGetCommandlet as well as Uninstall commandlet to expect the correct loglevel or content of logged messages.
Added logAtProccessable to IdeTestContextAssertions to check if a log-message was logged on PROCESSABLE-level.
Added .ide.software.version file to the npm software in the basic ide-test-project-ressource, since it was needed to test my implementation.

2024-12-20 10:09 UTC, hohwille commented on cli/src/main/java/com/devonfw/tools/ide/commandlet/VersionGetCommandlet.java
> +    VersionIdentifier installedVersion = commandlet.getInstalledVersion();
It seems that VersionGetCommandlet and EditionGetCommandlet are 95% identical.
We should move the code to a shared abstract base class `AbstractVersionOrEditionGetCommandlet`.

2024-12-20 18:26 UTC, hohwille commented
@jan-vcapgemini please have a look.
I reworked this PR and consider it as ready for review.
FYI: I also did some improvements and fixes of existing code that before was not part of this PR (e.g. `LocalToolCommandlet.getInstalledEdition()`).

2025-01-07 17:41 UTC, hohwille requested changes

2025-01-07 17:41 UTC, hohwille commented on cli/src/main/java/com/devonfw/tools/ide/tool/plugin/PluginBasedCommandlet.java
> +  public int uninstallPlugin(ToolPluginDescriptor plugin) {
`boolean` success flag instead of `int`?
Or throw an exception in case of failure/error?
Or do the logging in this method and keep `void` return type?
IMHO the last option makes to most sense.

2025-01-07 17:41 UTC, hohwille commented on cli/src/test/java/com/devonfw/tools/ide/commandlet/EditionGetCommandletTest.java
> +        IdeLogEntry.ofProcessable("ide install java"));
See my comment about the failing test...
```suggestion
    assertThat(context).log().hasEntries(IdeLogEntry.ofProcessable("java"));
```

2025-01-07 17:41 UTC, hohwille commented on cli/src/test/java/com/devonfw/tools/ide/commandlet/EditionGetCommandletTest.java
> +    assertThat(context).logAtProcessable().hasMessage("az");
here it seems vice versa. The output in the test was like this:
```
14:20:56.527 [main] - INFO  - c.d.tools.ide.log.IdeSubLoggerSlf4j - PROCESSABLE:No installation of tool az was found.
14:20:56.527 [main] - INFO  - c.d.tools.ide.log.IdeSubLoggerSlf4j - PROCESSABLE:The configured edition for tool az is az
14:20:56.527 [main] - INFO  - c.d.tools.ide.log.IdeSubLoggerSlf4j - PROCESSABLE:To install that edition call the following command:
14:20:56.527 [main] - INFO  - c.d.tools.ide.log.IdeSubLoggerSlf4j - PROCESSABLE:ide install az
```

So IMHO something is still broken with the implementation.

2025-01-20 12:19 UTC, hohwille approved these changes
@jan-vcapgemini thanks for taking over this PR. You did a really awesome job here 👍 
I only added minor suggestions but one review comment seems to indicate some kind of bug that we should discuss and if confirmed fix before merging.

2025-01-20 12:59 UTC, jan-vcapgemini commented on cli/src/test/java/com/devonfw/tools/ide/commandlet/EditionGetCommandletTest.java
> +    assertThat(context).log(IdeLogLevel.PROCESSABLE).hasMessage("basic");
I've enhanced the test description now.

2025-01-20 12:59 UTC, jan-vcapgemini commented on cli/src/test/java/com/devonfw/tools/ide/commandlet/EditionGetCommandletTest.java
> +    IdeTestContext context = newContext(PROJECT);
I've set `copyForMutation` to false for each `get` test now.

2025-01-20 13:11 UTC, hohwille commented on cli/src/test/java/com/devonfw/tools/ide/commandlet/EditionGetCommandletTest.java
> +    assertThat(context).log(IdeLogLevel.PROCESSABLE).hasMessage("basic");
OK, I figured it though not obvious from the code alone.
This is the configured edition even though no such edition exists:
https://github.com/devonfw/IDEasy/blob/fb9fb977272f93d39acf9b809f399e7fde0e6917/cli/src/test/resources/ide-projects/edition-version-get-uninstall/project/conf/ide.properties#L3

2025-01-20 14:26 UTC, hohwille commented
Thanks for fast and final perfection of this PR.
Ready for merge now! 👍

2025-01-20 14:26 UTC, merged